# Generated by Django 4.0.6 on 2022-07-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_popularcarmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='brand')),
                ('image', models.ImageField(upload_to='popular_car/', verbose_name='image')),
                ('model', models.CharField(max_length=30, verbose_name='model')),
                ('price', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='price')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'featured car',
                'verbose_name_plural': 'featured cars',
            },
        ),
    ]
